package com.at.pojo;

import java.util.Date;

public class tCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.id
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.codeName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String codename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.codeTypeName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String codetypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.parCode
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String parcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.sequenceNum
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Integer sequencenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.createdBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Date createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.creationDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.modifyBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String modifyby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.modifayDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Date modifaydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.id
     *
     * @return the value of t_code.id
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.id
     *
     * @param id the value for t_code.id
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.code
     *
     * @return the value of t_code.code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.code
     *
     * @param code the value for t_code.code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.codeName
     *
     * @return the value of t_code.codeName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getCodename() {
        return codename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.codeName
     *
     * @param codename the value for t_code.codeName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setCodename(String codename) {
        this.codename = codename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.codeTypeName
     *
     * @return the value of t_code.codeTypeName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getCodetypename() {
        return codetypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.codeTypeName
     *
     * @param codetypename the value for t_code.codeTypeName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setCodetypename(String codetypename) {
        this.codetypename = codetypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.parCode
     *
     * @return the value of t_code.parCode
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getParcode() {
        return parcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.parCode
     *
     * @param parcode the value for t_code.parCode
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setParcode(String parcode) {
        this.parcode = parcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.sequenceNum
     *
     * @return the value of t_code.sequenceNum
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Integer getSequencenum() {
        return sequencenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.sequenceNum
     *
     * @param sequencenum the value for t_code.sequenceNum
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setSequencenum(Integer sequencenum) {
        this.sequencenum = sequencenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.createdBy
     *
     * @return the value of t_code.createdBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Date getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.createdBy
     *
     * @param createdby the value for t_code.createdBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setCreatedby(Date createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.creationDate
     *
     * @return the value of t_code.creationDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.creationDate
     *
     * @param creationdate the value for t_code.creationDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setCreationdate(String creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.modifyBy
     *
     * @return the value of t_code.modifyBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.modifyBy
     *
     * @param modifyby the value for t_code.modifyBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setModifyby(String modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.modifayDate
     *
     * @return the value of t_code.modifayDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Date getModifaydate() {
        return modifaydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.modifayDate
     *
     * @param modifaydate the value for t_code.modifayDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setModifaydate(Date modifaydate) {
        this.modifaydate = modifaydate;
    }
}