package com.at.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class tCodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public tCodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodenameIsNull() {
            addCriterion("codeName is null");
            return (Criteria) this;
        }

        public Criteria andCodenameIsNotNull() {
            addCriterion("codeName is not null");
            return (Criteria) this;
        }

        public Criteria andCodenameEqualTo(String value) {
            addCriterion("codeName =", value, "codename");
            return (Criteria) this;
        }

        public Criteria andCodenameNotEqualTo(String value) {
            addCriterion("codeName <>", value, "codename");
            return (Criteria) this;
        }

        public Criteria andCodenameGreaterThan(String value) {
            addCriterion("codeName >", value, "codename");
            return (Criteria) this;
        }

        public Criteria andCodenameGreaterThanOrEqualTo(String value) {
            addCriterion("codeName >=", value, "codename");
            return (Criteria) this;
        }

        public Criteria andCodenameLessThan(String value) {
            addCriterion("codeName <", value, "codename");
            return (Criteria) this;
        }

        public Criteria andCodenameLessThanOrEqualTo(String value) {
            addCriterion("codeName <=", value, "codename");
            return (Criteria) this;
        }

        public Criteria andCodenameLike(String value) {
            addCriterion("codeName like", value, "codename");
            return (Criteria) this;
        }

        public Criteria andCodenameNotLike(String value) {
            addCriterion("codeName not like", value, "codename");
            return (Criteria) this;
        }

        public Criteria andCodenameIn(List<String> values) {
            addCriterion("codeName in", values, "codename");
            return (Criteria) this;
        }

        public Criteria andCodenameNotIn(List<String> values) {
            addCriterion("codeName not in", values, "codename");
            return (Criteria) this;
        }

        public Criteria andCodenameBetween(String value1, String value2) {
            addCriterion("codeName between", value1, value2, "codename");
            return (Criteria) this;
        }

        public Criteria andCodenameNotBetween(String value1, String value2) {
            addCriterion("codeName not between", value1, value2, "codename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameIsNull() {
            addCriterion("codeTypeName is null");
            return (Criteria) this;
        }

        public Criteria andCodetypenameIsNotNull() {
            addCriterion("codeTypeName is not null");
            return (Criteria) this;
        }

        public Criteria andCodetypenameEqualTo(String value) {
            addCriterion("codeTypeName =", value, "codetypename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameNotEqualTo(String value) {
            addCriterion("codeTypeName <>", value, "codetypename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameGreaterThan(String value) {
            addCriterion("codeTypeName >", value, "codetypename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameGreaterThanOrEqualTo(String value) {
            addCriterion("codeTypeName >=", value, "codetypename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameLessThan(String value) {
            addCriterion("codeTypeName <", value, "codetypename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameLessThanOrEqualTo(String value) {
            addCriterion("codeTypeName <=", value, "codetypename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameLike(String value) {
            addCriterion("codeTypeName like", value, "codetypename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameNotLike(String value) {
            addCriterion("codeTypeName not like", value, "codetypename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameIn(List<String> values) {
            addCriterion("codeTypeName in", values, "codetypename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameNotIn(List<String> values) {
            addCriterion("codeTypeName not in", values, "codetypename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameBetween(String value1, String value2) {
            addCriterion("codeTypeName between", value1, value2, "codetypename");
            return (Criteria) this;
        }

        public Criteria andCodetypenameNotBetween(String value1, String value2) {
            addCriterion("codeTypeName not between", value1, value2, "codetypename");
            return (Criteria) this;
        }

        public Criteria andParcodeIsNull() {
            addCriterion("parCode is null");
            return (Criteria) this;
        }

        public Criteria andParcodeIsNotNull() {
            addCriterion("parCode is not null");
            return (Criteria) this;
        }

        public Criteria andParcodeEqualTo(String value) {
            addCriterion("parCode =", value, "parcode");
            return (Criteria) this;
        }

        public Criteria andParcodeNotEqualTo(String value) {
            addCriterion("parCode <>", value, "parcode");
            return (Criteria) this;
        }

        public Criteria andParcodeGreaterThan(String value) {
            addCriterion("parCode >", value, "parcode");
            return (Criteria) this;
        }

        public Criteria andParcodeGreaterThanOrEqualTo(String value) {
            addCriterion("parCode >=", value, "parcode");
            return (Criteria) this;
        }

        public Criteria andParcodeLessThan(String value) {
            addCriterion("parCode <", value, "parcode");
            return (Criteria) this;
        }

        public Criteria andParcodeLessThanOrEqualTo(String value) {
            addCriterion("parCode <=", value, "parcode");
            return (Criteria) this;
        }

        public Criteria andParcodeLike(String value) {
            addCriterion("parCode like", value, "parcode");
            return (Criteria) this;
        }

        public Criteria andParcodeNotLike(String value) {
            addCriterion("parCode not like", value, "parcode");
            return (Criteria) this;
        }

        public Criteria andParcodeIn(List<String> values) {
            addCriterion("parCode in", values, "parcode");
            return (Criteria) this;
        }

        public Criteria andParcodeNotIn(List<String> values) {
            addCriterion("parCode not in", values, "parcode");
            return (Criteria) this;
        }

        public Criteria andParcodeBetween(String value1, String value2) {
            addCriterion("parCode between", value1, value2, "parcode");
            return (Criteria) this;
        }

        public Criteria andParcodeNotBetween(String value1, String value2) {
            addCriterion("parCode not between", value1, value2, "parcode");
            return (Criteria) this;
        }

        public Criteria andSequencenumIsNull() {
            addCriterion("sequenceNum is null");
            return (Criteria) this;
        }

        public Criteria andSequencenumIsNotNull() {
            addCriterion("sequenceNum is not null");
            return (Criteria) this;
        }

        public Criteria andSequencenumEqualTo(Integer value) {
            addCriterion("sequenceNum =", value, "sequencenum");
            return (Criteria) this;
        }

        public Criteria andSequencenumNotEqualTo(Integer value) {
            addCriterion("sequenceNum <>", value, "sequencenum");
            return (Criteria) this;
        }

        public Criteria andSequencenumGreaterThan(Integer value) {
            addCriterion("sequenceNum >", value, "sequencenum");
            return (Criteria) this;
        }

        public Criteria andSequencenumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sequenceNum >=", value, "sequencenum");
            return (Criteria) this;
        }

        public Criteria andSequencenumLessThan(Integer value) {
            addCriterion("sequenceNum <", value, "sequencenum");
            return (Criteria) this;
        }

        public Criteria andSequencenumLessThanOrEqualTo(Integer value) {
            addCriterion("sequenceNum <=", value, "sequencenum");
            return (Criteria) this;
        }

        public Criteria andSequencenumIn(List<Integer> values) {
            addCriterion("sequenceNum in", values, "sequencenum");
            return (Criteria) this;
        }

        public Criteria andSequencenumNotIn(List<Integer> values) {
            addCriterion("sequenceNum not in", values, "sequencenum");
            return (Criteria) this;
        }

        public Criteria andSequencenumBetween(Integer value1, Integer value2) {
            addCriterion("sequenceNum between", value1, value2, "sequencenum");
            return (Criteria) this;
        }

        public Criteria andSequencenumNotBetween(Integer value1, Integer value2) {
            addCriterion("sequenceNum not between", value1, value2, "sequencenum");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNull() {
            addCriterion("createdBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNotNull() {
            addCriterion("createdBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyEqualTo(Date value) {
            addCriterion("createdBy =", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotEqualTo(Date value) {
            addCriterion("createdBy <>", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThan(Date value) {
            addCriterion("createdBy >", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThanOrEqualTo(Date value) {
            addCriterion("createdBy >=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThan(Date value) {
            addCriterion("createdBy <", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThanOrEqualTo(Date value) {
            addCriterion("createdBy <=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIn(List<Date> values) {
            addCriterion("createdBy in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotIn(List<Date> values) {
            addCriterion("createdBy not in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyBetween(Date value1, Date value2) {
            addCriterion("createdBy between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotBetween(Date value1, Date value2) {
            addCriterion("createdBy not between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNull() {
            addCriterion("creationDate is null");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNotNull() {
            addCriterion("creationDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreationdateEqualTo(String value) {
            addCriterion("creationDate =", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotEqualTo(String value) {
            addCriterion("creationDate <>", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThan(String value) {
            addCriterion("creationDate >", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThanOrEqualTo(String value) {
            addCriterion("creationDate >=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThan(String value) {
            addCriterion("creationDate <", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThanOrEqualTo(String value) {
            addCriterion("creationDate <=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLike(String value) {
            addCriterion("creationDate like", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotLike(String value) {
            addCriterion("creationDate not like", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateIn(List<String> values) {
            addCriterion("creationDate in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotIn(List<String> values) {
            addCriterion("creationDate not in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateBetween(String value1, String value2) {
            addCriterion("creationDate between", value1, value2, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotBetween(String value1, String value2) {
            addCriterion("creationDate not between", value1, value2, "creationdate");
            return (Criteria) this;
        }

        public Criteria andModifybyIsNull() {
            addCriterion("modifyBy is null");
            return (Criteria) this;
        }

        public Criteria andModifybyIsNotNull() {
            addCriterion("modifyBy is not null");
            return (Criteria) this;
        }

        public Criteria andModifybyEqualTo(String value) {
            addCriterion("modifyBy =", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotEqualTo(String value) {
            addCriterion("modifyBy <>", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyGreaterThan(String value) {
            addCriterion("modifyBy >", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyGreaterThanOrEqualTo(String value) {
            addCriterion("modifyBy >=", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLessThan(String value) {
            addCriterion("modifyBy <", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLessThanOrEqualTo(String value) {
            addCriterion("modifyBy <=", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLike(String value) {
            addCriterion("modifyBy like", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotLike(String value) {
            addCriterion("modifyBy not like", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyIn(List<String> values) {
            addCriterion("modifyBy in", values, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotIn(List<String> values) {
            addCriterion("modifyBy not in", values, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyBetween(String value1, String value2) {
            addCriterion("modifyBy between", value1, value2, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotBetween(String value1, String value2) {
            addCriterion("modifyBy not between", value1, value2, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifaydateIsNull() {
            addCriterion("modifayDate is null");
            return (Criteria) this;
        }

        public Criteria andModifaydateIsNotNull() {
            addCriterion("modifayDate is not null");
            return (Criteria) this;
        }

        public Criteria andModifaydateEqualTo(Date value) {
            addCriterion("modifayDate =", value, "modifaydate");
            return (Criteria) this;
        }

        public Criteria andModifaydateNotEqualTo(Date value) {
            addCriterion("modifayDate <>", value, "modifaydate");
            return (Criteria) this;
        }

        public Criteria andModifaydateGreaterThan(Date value) {
            addCriterion("modifayDate >", value, "modifaydate");
            return (Criteria) this;
        }

        public Criteria andModifaydateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifayDate >=", value, "modifaydate");
            return (Criteria) this;
        }

        public Criteria andModifaydateLessThan(Date value) {
            addCriterion("modifayDate <", value, "modifaydate");
            return (Criteria) this;
        }

        public Criteria andModifaydateLessThanOrEqualTo(Date value) {
            addCriterion("modifayDate <=", value, "modifaydate");
            return (Criteria) this;
        }

        public Criteria andModifaydateIn(List<Date> values) {
            addCriterion("modifayDate in", values, "modifaydate");
            return (Criteria) this;
        }

        public Criteria andModifaydateNotIn(List<Date> values) {
            addCriterion("modifayDate not in", values, "modifaydate");
            return (Criteria) this;
        }

        public Criteria andModifaydateBetween(Date value1, Date value2) {
            addCriterion("modifayDate between", value1, value2, "modifaydate");
            return (Criteria) this;
        }

        public Criteria andModifaydateNotBetween(Date value1, Date value2) {
            addCriterion("modifayDate not between", value1, value2, "modifaydate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_code
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 19 09:34:15 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}