package com.at.pojo;

import java.util.Date;

public class tPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.id
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Integer id;

    private tCode tcode;

    public tCode getTcode() {
        return tcode;
    }

    public void setTcode(tCode tcode) {
        this.tcode = tcode;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.title
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.type
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.papaerSummary
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String papaersummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.createdBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.creationDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.modifyBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String modifyby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.modifyDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.fileName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String filename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.id
     *
     * @return the value of t_paper.id
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.id
     *
     * @param id the value for t_paper.id
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.title
     *
     * @return the value of t_paper.title
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.title
     *
     * @param title the value for t_paper.title
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.type
     *
     * @return the value of t_paper.type
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.type
     *
     * @param type the value for t_paper.type
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.papaerSummary
     *
     * @return the value of t_paper.papaerSummary
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getPapaersummary() {
        return papaersummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.papaerSummary
     *
     * @param papaersummary the value for t_paper.papaerSummary
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setPapaersummary(String papaersummary) {
        this.papaersummary = papaersummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.createdBy
     *
     * @return the value of t_paper.createdBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.createdBy
     *
     * @param createdby the value for t_paper.createdBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.creationDate
     *
     * @return the value of t_paper.creationDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.creationDate
     *
     * @param creationdate the value for t_paper.creationDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.modifyBy
     *
     * @return the value of t_paper.modifyBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.modifyBy
     *
     * @param modifyby the value for t_paper.modifyBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setModifyby(String modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.modifyDate
     *
     * @return the value of t_paper.modifyDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.modifyDate
     *
     * @param modifydate the value for t_paper.modifyDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.fileName
     *
     * @return the value of t_paper.fileName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.fileName
     *
     * @param filename the value for t_paper.fileName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }
}