package com.at.pojo;

import java.util.Date;

public class tUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userCode
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userPassword
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.gender
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.birthday
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.address
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userRole
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String userrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.paperNum
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Integer papernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.createdBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.creationDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.modifyBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private String modifyby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.modifyDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    private Date modifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userCode
     *
     * @return the value of t_user.userCode
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userCode
     *
     * @param usercode the value for t_user.userCode
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userName
     *
     * @return the value of t_user.userName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userName
     *
     * @param username the value for t_user.userName
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userPassword
     *
     * @return the value of t_user.userPassword
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userPassword
     *
     * @param userpassword the value for t_user.userPassword
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.gender
     *
     * @return the value of t_user.gender
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.gender
     *
     * @param gender the value for t_user.gender
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.birthday
     *
     * @return the value of t_user.birthday
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.birthday
     *
     * @param birthday the value for t_user.birthday
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.address
     *
     * @return the value of t_user.address
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.address
     *
     * @param address the value for t_user.address
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userRole
     *
     * @return the value of t_user.userRole
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getUserrole() {
        return userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userRole
     *
     * @param userrole the value for t_user.userRole
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setUserrole(String userrole) {
        this.userrole = userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.paperNum
     *
     * @return the value of t_user.paperNum
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Integer getPapernum() {
        return papernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.paperNum
     *
     * @param papernum the value for t_user.paperNum
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setPapernum(Integer papernum) {
        this.papernum = papernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.createdBy
     *
     * @return the value of t_user.createdBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.createdBy
     *
     * @param createdby the value for t_user.createdBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.creationDate
     *
     * @return the value of t_user.creationDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.creationDate
     *
     * @param creationdate the value for t_user.creationDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.modifyBy
     *
     * @return the value of t_user.modifyBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public String getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.modifyBy
     *
     * @param modifyby the value for t_user.modifyBy
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setModifyby(String modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.modifyDate
     *
     * @return the value of t_user.modifyDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.modifyDate
     *
     * @param modifydate the value for t_user.modifyDate
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
}