package com.at.dao;

import com.at.pojo.tCode;
import com.at.pojo.tCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface tCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int countByExample(tCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int deleteByExample(tCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int insert(tCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int insertSelective(tCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    List<tCode> selectByExample(tCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    tCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") tCode record, @Param("example") tCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int updateByExample(@Param("record") tCode record, @Param("example") tCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int updateByPrimaryKeySelective(tCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int updateByPrimaryKey(tCode record);
}