package com.at.dao;

import com.at.pojo.tPaper;
import com.at.pojo.tPaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface tPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int countByExample(tPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int deleteByExample(tPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int insert(tPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int insertSelective(tPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    List<tPaper> selectByExample(tPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") tPaper record, @Param("example") tPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbggenerated Mon Mar 19 09:34:15 CST 2018
     */
    int updateByExample(@Param("record") tPaper record, @Param("example") tPaperExample example);

    List<tPaper> selectMes(tPaper tpaper);
}